### PR TITLE
libserenity can now process multiple connections simultaneously.

### PR DESCRIPTION
**Pull request by lenonk**

### CODE REVIEW

**Comment by nirosys** [comment]
Heyyyy :D Thank you! I'll check it out tonight and get it merged in. :)

**Comment by lenonk** [comment]
Hey man, how are you?  Just so the change makes sense, the issue is that io_service can only process one async callback at a time since it's single threaded.

What happens is, when the connection class calls async_read_some(), and the callback is called, the endpoint is parsed out, and the request_dispatcher calls the API endpoint on the async_read_some() callback's time.  So if it takes a long time, or never returns, no new connections are ever serviced, because the async_accept() callback can't be run until the async_read_some() callback is complete.

The two options to fix it were to queue up the incoming requests and create a thread to handle them so that the async_read_some() callback can always return in a timely fashion, or just create a thread pool and have each thread call io_service::run().

I opted for the second option since it was easier and less prone to error, and I couldn't think of any really good reason to go the more complicated route.

**Comment by nirosys** [comment]
I'm doing pretty good :) How about yourself?

That makes total sense, thanks again. Took me a little bit to get back into the headspace, sorry for the delay. :) Along with your merge I also updated the travis build to a more recent boost version (1.69). What version are you using?

I've been so far away from C++ lately, need to spend some time giving this project some TLC.

**Comment by lenonk** [comment]
Doing pretty well man.  I actually don't know what version of boost we're using.  The framework just uses whatever is available on the box, so I'd say whatever comes with CentOS 6.  Personally, I'm doing all my development on my Linux box these days.  Working from home has it's advantages.  I don't have to use the Mac that assigned me.

What language are you working in mostly these days?  What, let me guess, Go?

**Comment by nirosys** [comment]
Cent6.. so I'm probably not far off with a 2 year old boost version lol.

Yea, I've been mostly using Go for work, and rust for side projects.

**Comment by lenonk** [comment]
We're moving to 8 by the end of the year.  Things are much better here than they were when you left.  The company is doing well and actually making money now.  We've been through a couple of CEOs, and pretty much the entire leadership team has been changed.

A couple of weeks ago they announced at a company meeting that since everything has worked out so well with everyone working at home due to COVID-19, everyone is welcome to work at home as much as they want going forward.  That didn't affect me since I don't live near an office, but I thought it was cool for everyone else.  As a side effect of that they're also doing away with PTO, I think.  They said something like if you need or want time off, just let your manager know and take it.  I'm not sure, it's not really fleshed out yet.

**Pull request merged**
